version: '3'
services:
  npm:
    build:
      context: .
    command: npm
    stdin_open: true
    tty: true
    volumes:
      - .:/app

  test:
    build:
      context: .
    command: npm run test
    stdin_open: true
    tty: true
    volumes:
      - .:/app
